#!/usr/bin/env node
/**
 * Measures how often each rule fires on writing nobody would call slop, next to
 * how often it fires on unedited model output, and writes bench/PRECISION.md.
 *
 *   node bench/precision.mjs           regenerate the table
 *   node bench/precision.mjs --check   fail if the committed table is stale
 *
 * The numbers are rates per 1,000 words, not detection accuracy. See the method
 * note in the generated file for what they do and do not support.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { lintText, rules } from "../dist/src/index.js";

const root = new URL("..", import.meta.url).pathname;
const corpus = join(root, "bench", "corpus");
const output = join(root, "bench", "PRECISION.md");

/** Every corpus file, newest rule set applied, grouped by the directory it sits in. */
function read(group) {
  const dir = join(corpus, group);
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => {
      const path = join(dir, f);
      return { name: `${group}/${f}`, result: lintText(relative(corpus, path), readFileSync(path, "utf8")) };
    });
}

const groups = { human: read("human"), machine: read("machine") };

const totals = Object.fromEntries(
  Object.entries(groups).map(([name, files]) => [name, files.reduce((n, f) => n + f.result.words, 0)]),
);

/** rule id -> { human: n, machine: n } */
const counts = new Map(rules.map((r) => [r.id, { human: 0, machine: 0 }]));
for (const [group, files] of Object.entries(groups)) {
  for (const { result } of files) {
    for (const f of result.findings) counts.get(f.rule)[group]++;
  }
}

const per1k = (n, words) => (words ? Math.round((n / (words / 1000)) * 10) / 10 : 0);

const rows = rules.map((rule) => {
  const c = counts.get(rule.id);
  const human = per1k(c.human, totals.human);
  const machine = per1k(c.machine, totals.machine);
  const ratio = c.human === 0 ? (c.machine === 0 ? "no data" : "clean") : `${Math.round((machine / human) * 10) / 10}x`;
  return { rule, human, machine, ratio, raw: c };
});

const fileRow = ({ name, result }) => `| \`${name}\` | ${result.words} | ${result.grade} | ${result.score} | ${result.findings.length} |`;

const md = `# Rule precision on a fixed corpus

Generated by \`node bench/precision.mjs\`. Do not edit by hand; CI fails when this
file does not match a fresh run.

## Method

Two corpora, both committed under \`bench/corpus\`:

The human corpus, ${totals.human.toLocaleString("en-US")} words, is public-domain prose written before any language
model existed: three literary and scientific works from the 1840s to 1860s, and two Python
Enhancement Proposals from 2001, which are the closest public-domain match to the register this
tool is aimed at, technical documentation kept in a repository.

The machine corpus, ${totals.machine.toLocaleString("en-US")} words, is unedited model output written for this corpus in
five shapes the tool actually sees: a README section, a pull request description, an article
introduction, a docs page and a set of commit messages.

Every rule runs over both. The table reports findings per 1,000 words in each corpus and the
ratio between them.

What the rules never see: front matter (YAML or TOML), fenced code including a fence inside a
blockquote, code quoted by four-space or tab indentation, inline code, link targets, bare URLs,
HTML tags and the contents of \`pre\` and \`code\` blocks. All of it is blanked before any rule
runs, so a dash in a diff a README quotes is not a finding. The exception is content indented
under a list item, which stays visible because list continuation is prose more often than it is
code.

What these numbers are not: they are not detection accuracy, and no row says a text was
machine-written. A rule that fires on the human corpus is not necessarily wrong: \`in order to\`
is filler whoever typed it. The human rate measures how much noise a rule adds to writing that
is already good, which is the cost a maintainer pays to keep the rule switched on. The machine
corpus was written by one model in one sitting, so a high ratio shows a rule catches what that
output looks like, not what every model produces. A corpus this size cannot support a percentage.

## Per rule

| rule | severity | human /1k | machine /1k | ratio |
|---|---|---:|---:|---|
${rows.map((r) => `| \`${r.rule.id}\` | ${r.rule.severity} | ${r.human} | ${r.machine} | ${r.ratio} |`).join("\n")}

\`clean\` means the rule never fired on the human corpus. \`no data\` means it fired on neither,
so this corpus says nothing about it. The machine corpus was typed as plain text, so the
typography rules (\`curly-quotes\`, \`emoji\`) are not exercised by it; their rows say nothing
about how well they work.

## Every finding on the human corpus

<!-- slop-ignore not-x-but-y ai-vocabulary -->

The full list, so the cost of running these rules on good writing is visible rather than
summarised.

| file | line | rule | message |
|---|---:|---|---|
${
  groups.human
    .flatMap(({ name, result }) => result.findings.map((f) => `| \`${name}\` | ${f.line} | \`${f.rule}\` | ${f.message.replace(/\|/g, "\\|")} |`))
    .join("\n") || "| | | | none |"
}

Most of these are real dashes in nineteenth-century prose and \`--\` in a 2001 style guide.
They are not mistakes by the rule: the dashes are there. They are a house rule for text in a
repository, and this table is the argument for keeping that rule at the severity it has rather
than a claim about who wrote Darwin.

## Per file

| file | words | grade | score | findings |
|---|---:|---|---:|---:|
${[...groups.human, ...groups.machine].map(fileRow).join("\n")}

## Sources

See [\`corpus/MANIFEST.md\`](corpus/MANIFEST.md) for the origin and licence of every file.
`;

if (process.argv.includes("--check")) {
  const current = readFileSync(output, "utf8");
  if (current !== md) {
    console.error("bench/PRECISION.md is stale; run `node bench/precision.mjs` and commit the result");
    process.exit(1);
  }
  console.log(`precision table up to date (${rules.length} rules, ${totals.human + totals.machine} words)`);
} else {
  writeFileSync(output, md);
  console.log(`wrote bench/PRECISION.md (${rules.length} rules, human ${totals.human} words, machine ${totals.machine} words)`);
}
