#!/usr/bin/env node
/**
 * Measures every rule against correct native typography in thirteen languages
 * and writes bench/TYPOGRAPHY.md.
 *
 *   node bench/typography.mjs           regenerate the table
 *   node bench/typography.mjs --check   fail if the committed table is stale
 *
 * The question this answers is not whether a text is machine-written. It is
 * whether a rule fires on a language because that language writes differently,
 * which would penalise a writer for their own punctuation. Rates are findings
 * per 1,000 words, the same measure bench/precision.mjs uses, so the numbers in
 * the two files can be read side by side.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { lintText, rules } from "../dist/src/index.js";

const root = new URL("..", import.meta.url).pathname;
const dir = join(root, "bench", "typography");
const output = join(root, "bench", "TYPOGRAPHY.md");

/** Language code -> display name. The code is the filename prefix. */
const NAMES = {
  de: "German", en: "English", es: "Spanish", fi: "Finnish", fr: "French",
  hu: "Hungarian", it: "Italian", ja: "Japanese", nl: "Dutch", pl: "Polish",
  pt: "Portuguese", ru: "Russian", tr: "Turkish", zh: "Chinese",
};

/**
 * Nineteenth-century editions reach us through transcribers, and several of them
 * typed the em dash as two hyphens. Where those hyphens are attached to the next
 * word, as they are in the French, Spanish, Portuguese and Dutch files, the rule's
 * spaced-double-hyphen branch does not match them, so the file scores clean for a
 * reason that has nothing to do with the language. This is the one transformation
 * used to measure that gap: every `--` becomes the em dash the transcriber meant.
 * It is applied in memory only. The committed corpus is never rewritten.
 */
const asTypeset = (text) => text.replace(/--/g, "\u2014");

/** One corpus file: its language, its word count and everything the rules found in it. */
function measure(path, name, lang) {
  const text = readFileSync(path, "utf8");
  return {
    name,
    lang,
    chars: [...text].length,
    doubleHyphens: (text.match(/--/g) ?? []).length,
    result: lintText(name, text),
    // English is left alone: two of its five files are Python style guides where a
    // double hyphen is a command-line flag, and restoring those would invent dashes.
    typeset: lang === "en" ? lintText(name, text) : lintText(name, asTypeset(text)),
  };
}

// Corpus files are named `<language code>-<author>-<work>.md`; MANIFEST.md is not one.
const files = readdirSync(dir)
  .filter((f) => /^[a-z]{2}-.+\.md$/.test(f))
  .sort()
  .map((f) => measure(join(dir, f), f, f.slice(0, f.indexOf("-"))));

// English is not in this corpus: bench/corpus/human already holds five English
// files measured the same way, and they are the baseline every other row is read
// against. Reusing them keeps one English sample rather than two that disagree.
const englishDir = join(root, "bench", "corpus", "human");
const english = readdirSync(englishDir)
  .filter((f) => f.endsWith(".md"))
  .sort()
  .map((f) => measure(join(englishDir, f), f, "en"));

const all = [...english, ...files];
const langs = [...new Set(all.map((f) => f.lang))].sort();

/** language -> total words, and language -> rule id -> finding count. */
const words = new Map(langs.map((l) => [l, 0]));
const counts = new Map(langs.map((l) => [l, new Map(rules.map((r) => [r.id, 0]))]));
for (const f of all) {
  words.set(f.lang, words.get(f.lang) + f.result.words);
  for (const finding of f.result.findings) {
    const row = counts.get(f.lang);
    row.set(finding.rule, row.get(finding.rule) + 1);
  }
}

const per1k = (n, w) => (w ? Math.round((n / (w / 1000)) * 10) / 10 : 0);
const rate = (lang, id) => per1k(counts.get(lang).get(id), words.get(lang));
const total = (lang) => [...counts.get(lang).values()].reduce((a, b) => a + b, 0);

/** Rules that fire somewhere; the rest are listed as a sentence instead of an empty column. */
const fired = rules.filter((r) => langs.some((l) => counts.get(l).get(r.id) > 0));
const silent = rules.filter((r) => !fired.includes(r));

const langCol = langs.map((l) => `${NAMES[l]}`).join(" | ");
const align = langs.map(() => "---:").join(" | ");

const md = `# Every rule against correct native typography

Generated by \`node bench/typography.mjs\`. Do not edit by hand; CI fails when this
file does not match a fresh run.

## Method

Thirteen excerpts of published prose, one per language, all written before any language
model existed and all in the public domain. Each was set by a publisher or a translator
who applied that language's own typographic conventions: the spaced em dash of French,
the raya that opens Spanish dialogue, the en dash Hungarian uses for the same job, the
Russian em dash that stands in for a missing verb, the guillemets of Italian, the low
quotation mark of Polish and German, the ideographic comma and corner brackets of Japanese.
None of it is a mistake. All of it is what a careful writer in that language is supposed
to type.

English is the fifth to ninth row of \`bench/corpus/human\`, measured the same way and
carried here unchanged, so the English baseline in this file and the human baseline in
[\`PRECISION.md\`](PRECISION.md) are the same numbers.

Rates are findings per 1,000 words. \`bench/typography/MANIFEST.md\` names every text, its
author, its date, its source and its licence.

## Words measured

| language | files | words | findings | per 1,000 words |
|---|---:|---:|---:|---:|
${langs.map((l) => `| ${NAMES[l]} | ${all.filter((f) => f.lang === l).length} | ${words.get(l)} | ${total(l)} | ${per1k(total(l), words.get(l))} |`).join("\n")}

## Per rule, per language

Findings per 1,000 words. Only the rules that fire somewhere have a column here; the
${silent.length} that fire nowhere in this corpus are listed below the table.

| rule | severity | ${langCol} |
|---|---|${align.replace(/---:/g, "---:")}|
${fired.map((r) => `| \`${r.id}\` | ${r.severity} | ${langs.map((l) => rate(l, r.id)).join(" | ")} |`).join("\n")}

Silent on every language in this corpus: ${silent.map((r) => `\`${r.id}\``).join(", ")}.
A rule that fires nowhere here is not thereby safe; it means this corpus does not
exercise it. These files are continuous prose, so the rules that need a heading, a bold
label, a list marker or an emoji have nothing to match, whatever language they are in.

## Per file

| file | words | grade | score | findings |
|---|---:|:--:|---:|---:|
${all.map((f) => `| \`${f.lang === "en" ? `corpus/human/${f.name}` : `typography/${f.name}`}\` | ${f.result.words} | ${f.result.grade} | ${f.result.score} | ${f.result.findings.length} |`).join("\n")}

## What the transcription hides

Several of these files reach us with the em dash typed as two hyphens attached to the
word that follows, which is how the transcriber rendered a dash that the printed edition
set as \`\u2014\`. The rule matches a double hyphen only when it stands between spaces, so those
files score clean for a reason that belongs to the transcription and not to the language.
The right-hand column repeats the measurement with every \`--\` restored to the em dash the
transcriber was standing in for; nothing else about the file changes and the committed
corpus is untouched.

| language | \`--\` in the file | \`dash\` /1k as transcribed | \`dash\` /1k as typeset |
|---|---:|---:|---:|
${
  langs
    .filter((l) => all.some((f) => f.lang === l && f.doubleHyphens > 0))
    .map((l) => {
      const group = all.filter((f) => f.lang === l);
      const hyphens = group.reduce((n, f) => n + f.doubleHyphens, 0);
      const before = group.reduce((n, f) => n + f.result.findings.filter((x) => x.rule === "dash").length, 0);
      const after = group.reduce((n, f) => n + f.typeset.findings.filter((x) => x.rule === "dash").length, 0);
      return `| ${NAMES[l]} | ${hyphens} | ${per1k(before, words.get(l))} | ${per1k(after, words.get(l))} |`;
    })
    .join("\n")
}

English is listed for comparison but is never restored: two of its five files are Python
style guides in which a double hyphen is a command-line flag rather than a dash, so its
two columns are the same number.

Read the right-hand column as the rate a writer of that language would meet today, since
nobody types a dash as two hyphens in a README. Read the left-hand column as a warning
about corpora: a rule can look harmless on a language because of how the file was typed.

## What fires, and on what

One example per rule per language, so the table above can be checked against the text
that produced it.

| language | rule | excerpt |
|---|---|---|
${
  langs
    .flatMap((l) => {
      const seen = new Set();
      return all
        .filter((f) => f.lang === l)
        .flatMap((f) => f.result.findings.map((x) => ({ f, x })))
        .filter(({ x }) => !seen.has(x.rule) && seen.add(x.rule))
        .map(({ x }) => `| ${NAMES[l]} | \`${x.rule}\` | ${String(x.excerpt ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ").trim() || "—"} |`);
    })
    .join("\n") || "| | | none |"
}

## Sources

See [\`typography/MANIFEST.md\`](typography/MANIFEST.md) for the origin and licence of every
file, and [\`../docs/typography-across-languages.md\`](../docs/typography-across-languages.md)
for what these numbers mean and what should be done about them.
`;

if (process.argv.includes("--check")) {
  if (readFileSync(output, "utf8") !== md) {
    console.error("bench/TYPOGRAPHY.md is stale; run `node bench/typography.mjs` and commit the result");
    process.exit(1);
  }
  console.log(`typography table up to date (${langs.length} languages, ${[...words.values()].reduce((a, b) => a + b, 0)} words)`);
} else {
  writeFileSync(output, md);
  console.log(`wrote bench/TYPOGRAPHY.md (${langs.length} languages, ${[...words.values()].reduce((a, b) => a + b, 0)} words)`);
}
